### ISSUE TITLE
Reset password

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#1]
US
**jako**: Użytkownik który posiada konto w systemie
**chciałbym**: mieć funkcjonalność pozwalająca na reset hasła przy logowaniu po przez....(kliknięcie guzika "Ustaw hasła"). Po wciśnięciu przycisku "Ustaw nowe hasło" system wys. okno dialogowe, gdzie prosi użytkownika o podanie adresu e-mail. Na wskazany adres email przychodzi link z restem hasła.
**aby**: Ustawić nowe hasło.

Makieta:
![Image](https://github.com/user-attachments/assets/a9b3cda2-26ce-4b0c-a6a3-2fc9ca97475b)

Wycena:
Analiza: 1 g
Front: 3 g
Test: 1 g
PM: 1 g

**Comment by hayasaka5** [comment]
o

**Comment by hayasaka5** [comment]
Reset Password link
https://finance-tracker-react-rho.vercel.app/PasswordReset
[reset.password.page.txt](https://github.com/user-attachments/files/17632101/reset.password.page.txt)

**Comment by hayasaka5** [comment]
Test Reset page
[test.reset.pdf](https://github.com/user-attachments/files/17636539/test.reset.pdf)
