### ISSUE TITLE
Log in and sign in

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#3]
**jako**: Uzytkownik ktory сhcę założyć konto lub już posiada
**chciałbym**: mieć funkcjonalność pozwaląca na rejestracje oraz logowanie...
  1. Rejestracja 
    1.1. Użytkownik, który nie posiada konta, wchodzi na stronę (strona "Sign Up" jest główna)
    1.2. Użytkownik podaje adres e-mail, hasło i za tym wpisuje hasło jeszcze raz dla potwierdzenia poprawności).
    1.3. Jezeli wszystko się zgadza, to po przyciskaniu uzytkownikiem "Sign Up" przenosi na stronę głowną, jak nie to występuje błąd.
    1.4. Użytkownik pisadający konto, może wcisnąć "Sign In" i się zalogować.
Makieta:
![Image](https://github.com/user-attachments/assets/99ef66f2-ce11-4ed1-a9da-88db90d2a1d4)

  2. Logowanie 
    2.1. Użytkownik posiadający konto na platformie, po naciskaniu "Sign In" podaje adres mailowy oraz hasło.
    2.2. Jak dane się zgadzają, użytkownik przenosi się na stronę główną
    2.3. Jeżeli użytkownik zapomniał hasło, wciska "Forgot password?" i resetuje hasło
    2.4. Użytkownik nie posiadający konta, ma przycisk "Sign Up", gdzie może się zarejestrować.
Makieta:
![Image](https://github.com/user-attachments/assets/2de593ad-5ef1-4a0c-92f9-1068f1d23a69)

aby: Rejestracja konta oraz logowania (jeżeli użytkownik już posiada konto)

**Wycena**: 

1. Analiza - 2 g
2. Front -  4 g
3. Test - 3 g
4. PM - 1 g

**Comment by hayasaka5** [comment]
Sign Up link
https://finance-tracker-react-rho.vercel.app/SignUp
Sign In link
https://finance-tracker-react-rho.vercel.app/SignIn
[sign up and sign in pages.txt](https://github.com/user-attachments/files/17632063/sign.up.and.sign.in.pages.txt)

**Comment by hayasaka5** [comment]
Test Sign In,[test.signup.signin.pdf](https://github.com/user-attachments/files/17636475/test.signup.signin.pdf)
 Sign Up
