### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#4]
US
**jako**: Użytkownik który posiada konto w systemie
**chciałbym**: mieć mozliwość korzystania ze strony ta serwisu. Wyniki transakcji były wyświetlone na wykresach
**aby**: Mieć pełną funkconalność i narzędzia

Makieta
Poniżej będą znajdować się komponenty główne: grafik transakcij za ostatnie 6 miesięcy ze stosunkiem środków na każdy miesiąc oraz z całkowitą różnicą dochodów i wydatków. Ten grafik będzie zmiał wartość w zalezności od wpisanych danych przy nowej transakcji. 
![Image](https://github.com/user-attachments/assets/35d60d3d-13a8-4ad6-83c3-19d22019b99b)
 
Po prawej stronie od głownego grafiku, muszą się znajdować 2 wykresy kołowych: z wydatkami i z dochodami. Informacja o źrodle dochodów i odwrotnie. Jak uzytkownik wprowadza nową transakcję, wykresy przyjmują dane.

Makieta
![Image](https://github.com/user-attachments/assets/319d091a-e810-4038-b0b2-d542fd698f0d)

Na samym dole musi znajdować się historia transakcij z danymi użytkownika, datą, kategoriją lub źródłem, ilością wydanych lub otrzymanych pięniedzy.
Równiez ma być przycisk "Add transactions", który da mozliwość stworzyć nową transakcjie. Obok tego przycisk "See more", który pozwala zobaczyć wiele poprzednich transakcij.

Makieta
![Image](https://github.com/user-attachments/assets/5dc70a6c-ad44-4366-a1f2-f2851bde1703)

**Wycena**:
Analiza: 4 g
Front: 16 g
Test: 8 g
PM: 3 g

**Comment by hayasaka5** [comment]
Test Dashboard Transactions[test.dashboard.transactions.pdf](https://github.com/user-attachments/files/17777273/test.dashboard.transactions.pdf)
