### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#5]
**jako:** Użytkownik który posiada konto w systemie
**chciałbym:** mieć menu nawigacyjne
**aby:** wchodzić do stron ta korzystać się z narzędź za pomocą menu z nawigacją 

Na górze menu musi być logo/nazwa serwisu. Poniżej linki nawigacyjne (Dashboard, Transactions i Settings(na dole))  z nazwami strony oraz ikonami. Przy wchodzeniu na stronę element strony ma zmienić kolor.
Menu powiino być dostępne na każdej stronie

Makieta
![Image](https://github.com/user-attachments/assets/c9b532b2-906b-4b21-8af8-84a9647fa562)

**Wycena**
Analiza: 1 g
Front: 3 g
Test: 2 g
PM: 1 g

**Comment by hayasaka5** [comment]
Left menu component
[leftmenu.txt](https://github.com/user-attachments/files/17775899/leftmenu.txt)
