### ISSUE TITLE
Strona Transactions

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#6]
US
**jako:** Użytkownik który posiada konto w systemie
**chciałbym:** Okienko, które pozwala stworzyć transakcję, razem z tym wypełniać pola danymi dla informacji o tej trans.
**aby:** przy kazdej nowej trans. podać całkowitą informację

Na górze strony znajduje się nazwa strory oraz informacja użytkownika. 

Przycisk "Add transactions". Po aktywacji tego przycisku wypada okno w jakim są pola, gdzie wybieramy lub wpisujemy informację.
Okmo musi zawierać następne wypadające pola (w polu "Transactions" oraz "Amount" dane wpisujemy ręcznie): 

1. Transactions (źródło lub kierunek)
2. Category (w jakiej kategorji jest wydatek czy dochod)
3. Date (data transakcji)
4. Amount (ile wynosiła kwota)
Żadne pole nie może zostać puste.
Makieta
![Image](https://github.com/user-attachments/assets/543347e5-7fde-48a7-b579-c20a29d5d929)

Tabela informacyjna ponizej musi zawierać wszystkie dane wpisane wcześniej.
Jak nie ma zadnych trans. proszę wyświetlać w polu wiadomość np. "no trans. yet"

Makieta
![Image](https://github.com/user-attachments/assets/6f1d64e4-a3ba-4404-94f3-c70b9053dfc4)

Jak transakcja pojawi się w tabeli, dodać mozliwość sprawdzenia wszystkiej informacji
Makieta
![Image](https://github.com/user-attachments/assets/46ac3a08-c957-4ef9-9f15-0944e571274d)

**Wycena** 
Analiza 4 g
Front 14 g
Test 5 g
PM 3 g

**Comment by hayasaka5** [comment]
Transactions component
[transactions.txt](https://github.com/user-attachments/files/17776046/transactions.txt)

**Comment by hayasaka5** [comment]
Test Dashboard Transactions [test.dashboard.transactions.pdf](https://github.com/user-attachments/files/17777282/test.dashboard.transactions.pdf)
ons
