### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#7]
US
**jako:** Użytkownik który posiada konto w systemie
**chciałbym:** Mieć funkcjonalną stronę Ustawienia 
**aby:** mieć mozliwość dodawać lub zmieniać informację 
Na stronie znajdują się 2 okienka, gdzie są pospisane pola, w jakich podajemy dodatkową informację o sobie (np. imię a nazwisko), zdjęcie profilu, które mozey znaleźć na komputerze. Również na tej stronie mozna dodać email oraz zmienić hasło. Wszystkie dane mozna zapisać przez przycisk "Save"

Makieta
![Image](https://github.com/user-attachments/assets/06e790b9-76b0-4129-ba30-710a825974f8)

**Wycena:**
Analiza: 2 g
Front: 7 g 
Test: 4 g
PM: 2 g

**Comment by hayasaka5** [comment]
Add transaction component 
[addtransaction.txt](https://github.com/user-attachments/files/17777374/addtransaction.txt)

**Comment by hayasaka5** [comment]
Settings component
[settings.txt](https://github.com/user-attachments/files/17777417/settings.txt)

**Comment by hayasaka5** [comment]
Settings test
[test.settings.pdf](https://github.com/user-attachments/files/17778247/test.settings.pdf)
