### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by RostyslavBkl** [RostyslavBkl/Test1#8]
**jako:** Użytkownik który posiada konto w systemie
**chciałbym:** na każdej stronie żeby było widać header
**aby:** mięc informację o stronie z której się korzysta użytkownik
Na górze każdej strony (Dashboard, Settings etc) zrobić widocznym nazwę strony, na jakiej jesteś oraz adres dane użytkownika, czyli adres mailowy. Jeżeli użytkownik nie jest zarejestowany, to niech będzie napisane np. "user isnt logged in"

Makieta 1 
![Image](https://github.com/user-attachments/assets/928777fc-e233-4c5e-9a20-18b457457ca4)

Makieta 2
![Image](https://github.com/user-attachments/assets/694f1d38-5796-439d-bb99-d5e3b2968429)

*Wycena:**
Analiza: 1 g
Front: 2 g
Test: 1 g
PM: 1 g

**Comment by hayasaka5** [comment]
Header component
[header.txt](https://github.com/user-attachments/files/17781324/header.txt)

**Comment by hayasaka5** [comment]
Header test
[test.header.pdf](https://github.com/user-attachments/files/17789891/test.header.pdf)
